services:
  db:
    image: postgres:16
    container_name: calculate_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: calculate_redis

  calculate:
    image: calculate_image
    build:
      context: .
    container_name: calculate_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: sh -c "alembic upgrade head && python main.py"

volumes:
  postgresdata:
    driver: local
